### PR TITLE
Remove jdk7 from travis

### PR DESCRIPTION
**Pull request by jmuk**
Sorry, these jdks cause errors actually.

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
The problem isn't the JDKs, the problem is that we have Java 8 code. We actually want to support Java 7.

**Comment by jmuk** [comment]
So should we fix the compile errors of Java 7 instead?

**Comment by garrettjonesgoogle** [comment]
I think we should.

**Comment by jmuk** [comment]
Ok, will abandon this PR.

**Comment by tbetbetbe** [comment]
I've just raised #8 to track this.
If either of you want to jump and fix it before @chrisdunelm gets in tomorrow, I'm sure he'd appreciate it ;)

**Pull request closed without merging**
