### PR TITLE
Reduce # of forked JVMs and initial heap size

### PR DESCRIPTION
**Pull request by saicheems**
Should close the case of the mysterious flaky builds.

### CODE REVIEW

**Comment by saicheems** [comment]
Prior art:
https://discuss.gradle.org/t/travis-ci-org-gradle-launcher-daemon-client-daemondisappearedexception-gradle-build-daemon-disappeared-unexpectedly-it-may-have-been-killed-or-may-have-crashed/13106/2

**Comment by saicheems** [comment]
Feeling pretty good about this one, ptal

**Comment by garrettjonesgoogle** [comment]
I like it, LGTM

**Comment by vchudnov-g** [comment]
LGTM. Can we be more aggressive with the parallelization or is this the best we can do and not run into problems?

Thanks for solving this!

**Comment by saicheems** [comment]
Luckily the number of parallel jobs is a property of Travis, so we can increase that number in the UI. I'll mess with it a bit in future PRs to see if it does anything.

**Pull request merged**
