### PR TITLE
Delete GoContextCommon

### PR DESCRIPTION
**Pull request by pongad**
Even more can go away after https://github.com/googleapis/toolkit/pull/673 lands.

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
LGTM after the one comment is addressed.

**Comment by pongad** [comment]
@garrettjonesgoogle I do not see a comment. Did it get lost somewhere?

**Comment by garrettjonesgoogle** [comment]
Scroll up? "make a constant out of 75"

**Comment by pongad** [comment]
Huh! I'm still not seeing the comments but will do

**Pull request merged**
