### PR TITLE
Fix name conflict with grpc stub

### PR DESCRIPTION
**Pull request by michaelbausor**
Use fully qualified name for grpc stub to avoid conflicting with the generated class name

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
LGTM

**Comment by michaelbausor** [comment]
Updated to add leading backslash and remove unused function, PTAL

**Comment by michaelbausor** [comment]
Updated to remove backlashes from use statements, PTAL

**Comment by garrettjonesgoogle** [comment]
LGTM

**Pull request merged**
