### PR TITLE
Rename Rakefile tasks

### PR DESCRIPTION
**Pull request by geigerj**
#1660 renamed some tasks to introduce `ci:acceptance`, but in the wrong
place. The acceptance task should be runnable in all cases, even when
there are no smoke tests.

### CODE REVIEW

**Comment by landrito** [comment]
Should this also make the generated smoke tests run on `rake smoke_test`?

**Comment by geigerj** [comment]
@landrito Isn't that already the case with the task defined here: https://github.com/googleapis/toolkit/pull/1671/files#diff-fdaf77e823c0b9f1416f7386beb45fc2R60

**Comment by landrito** [comment]
Blah, brain fart. LGTM

**Comment by landrito** [comment]
Oh wait, I retract my LGTM. 

I mean to say these two tasks should be merged.

https://github.com/googleapis/toolkit/blob/master/src/main/resources/com/google/api/codegen/ruby/Rakefile.snip#L62

https://github.com/googleapis/toolkit/blob/master/src/main/resources/com/google/api/codegen/ruby/Rakefile.snip#L90

**Comment by geigerj** [comment]
@landrito I don't know about merged, but I made smoke tests are a subset of acceptance. (Especially with partial GAPICs, we might expect that there are manual, non-smoke test acceptance tests that you might want to be able to invoke separately.)

**Comment by landrito** [comment]
Hm. Okay. I think I buy that a distinction is still needed.

**Pull request merged**
