### PR TITLE
Remove path template structs

### LINKED ISSUE #67: Remove path structs from go codegen
Instead of generating types and methods for parsing/generating resource names, produce functions analogous to other languages.

ex (via @jba):
```
func ParseProjectPath(path string) (string, error) { return gax.SplitPath1(path)  }
func ProjectPath(projectName string) string { return "projects/" + projectName }

func ParseLogPath(string path) (string, string, error) { return gax.SplitPath2(path) }
func LogPath(projectName, logName string) string { return "projects/" + projectName + "/logs/" + logName) }
```

### PR DESCRIPTION
**Pull request by saicheems**
Resolves #67

### CODE REVIEW

**Comment by saicheems** [comment]
@jba 
@pongad 
@jmuk 
@vchudnov-g

**Comment by jba** [comment]
LGTM

**Comment by jmuk** [comment]
LGTM++

**Comment by pongad** [comment]
++lgtm

**Pull request merged**
