### PR TITLE
git merge origin master

### PR DESCRIPTION
**Pull request by andreamlin**
Integrate the latest origin/master changes into the discogapic branch.

### CODE REVIEW

**Comment by andreamlin** [comment]
PTAL.

**Comment by garrettjonesgoogle** [comment]
Could you list the steps you took to produce this? (reviewing that will be more fruitful than looking at the diff of the merge)

**Comment by andreamlin** [comment]
I did a `git merge master`, then a `git rebase master`.

**Comment by garrettjonesgoogle** [comment]
Were there merge conflicts you had to fix?

**Comment by andreamlin** [comment]
Yes, I did have to fix merge conflicts. With the exception of the discogapic resources, all of the test resources (.yaml, .json, .baseline) and snippets are the versions from the master branch.

**Comment by garrettjonesgoogle** [comment]
LGTM let's just get this merged

**Comment by andreamlin** [comment]
There's time later for a more thorough review when the discogapic branch is merged into master.
Thanks!

**Pull request merged**
