### PR TITLE
Enum extraction from discovery doc

### PR DESCRIPTION
**Pull request by chrisdunelm**
Add correct enum handling in C#, with all other languages treating enums like strings (as is their current behaviour

### CODE REVIEW

**Comment by jskeet** [comment]
This looks like it's probably okay - but do we have any tests that show the effect of this?

**Comment by chrisdunelm** [comment]
Unfortunately the current test cases don't seem to include any methods with enum parameters.
So, no, I don't think there's a test case currently.
I've manually generated code in all 7 languages that includes an enum, and verified it's OK, but I guess I should really add a test case.

**Comment by garrettjonesgoogle** [comment]
Adding @pongad for him to take a look.

**Comment by pongad** [comment]
We'll probably want tests for this, but otherwise it looks good to me. This will most likely affect #249, which is OK since that's still a work in progress and there're still some design works do we done there.

**Comment by chrisdunelm** [comment]
Thanks Michael,
I've added adexchangebuyer to the set of tested APIs, as this exercises the enum code.
Is this a sufficient test?

**Comment by pongad** [comment]
Ah! Sorry I didn't see it. LGTM.

Hopefully we'll able to do more streamlined testing, but that's way out of the scope of this PR.

**Pull request merged**
