### PR TITLE
Remove CallOption vararg

### PR DESCRIPTION
**Pull request by saicheems**
Requires all configuration to be performed on initialization.

### CODE REVIEW

**Comment by saicheems** [comment]
Based on email thread, lmk if this is reasonable

@pongad 
@vchudnov-g 
@jba 
@jmuk

**Comment by jba** [comment]
I'm in favor of doing this, but there's more to it, isn't there? If the timeout is going to be passed in the context, doesn't the retry logic need to use that instead of the timeout in CallOptions?

**Comment by saicheems** [comment]
The timeout in CallOptions is applied to the context in gax.Invoke
Any timeout applied to the context the user passes in is either ignored, or overrides the default provided:
https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/go_library.baseline#L119

**Comment by jba** [comment]
On Tue, May 31, 2016 at 5:13 PM Sai Cheemalapati <notifications@github.com>
wrote:

> The timeout in CallOptions is applied to the context in gax.Invoke
>
But that is the problem — we now want the timeout to propagated via the
context, not the call options.

So if the user does

    ctx, _ = context.WithTimeout(ctx, time.Second)
    client.SomeMethod(ctx, arg)

then gax.Invoke should observe the 1-second timeout from the context.

I don't think we want timeout to be in CallOptions at all.

**Comment by saicheems** [comment]
I see...but if we remove the Timeout option and the user doesn't apply a timeout to the context, then there's no default limit on the call.

The settings design for all other veneers includes a default timeout that the API owner can set for each call - so how can we enforce that without the option?

**Comment by jba** [comment]
How about something like this:

if _, ok := ctx.Deadline(); !ok {
  // no deadline in ctx; use default
  ctx = context.WithTimeout(ctx, defaultTimeoutForMethod)
}

**Comment by saicheems** [comment]
SGTM, I made a pull in gax-golang to change Invoke's behavior to give custom deadlines precedence

**Comment by jba** [comment]
LGTM.

**Pull request merged**
