### PR TITLE
Migrate Python to MVVM

### LINKED ISSUE #348: Refactor Python generation to use the MVVM pattern
FYI @jmuk @bjwatson @geigerj

### LINKED ISSUE #490: Share license section in one place for each language
### What:

Share license section in one place (like `common.snip`) for each language.
### Why:

Keep it DRY. We currently duplicate our generated file licenses across multiple `.snip` files for each language:

```
toolkit$ git grep licenseSection
src/main/resources/com/google/api/codegen/nodejs/main.snip:  {@licenseSection(service)}
src/main/resources/com/google/api/codegen/nodejs/main.snip:@private licenseSection(service)
src/main/resources/com/google/api/codegen/nodejs/message.snip:  {@licenseSection()}
src/main/resources/com/google/api/codegen/nodejs/message.snip:@private licenseSection()
src/main/resources/com/google/api/codegen/php/main.snip:    {@licenseSection(xapiClass)}
src/main/resources/com/google/api/codegen/php/main.snip:@private licenseSection(xapiClass)
src/main/resources/com/google/api/codegen/py/main.snip:    {@licenseSection(service)}
src/main/resources/com/google/api/codegen/py/main.snip:@private licenseSection(service)
src/main/resources/com/google/api/codegen/py/message.snip:    {@licenseSection()}
src/main/resources/com/google/api/codegen/py/message.snip:@private licenseSection()
src/main/resources/com/google/api/codegen/ruby/main.snip:  {@licenseSection(service)}
src/main/resources/com/google/api/codegen/ruby/main.snip:@private licenseSection(service)
src/main/resources/com/google/api/codegen/ruby/message.snip:    {@licenseSection()}
src/main/resources/com/google/api/codegen/ruby/message.snip:@private licenseSection()
```
### Tracking
Pre-requisite: MVVM conversion should be done first.

- [x] Java
- [x] PHP
- [x] C#
- [x] Node.js
- [x] Ruby
- [ ] Python
- [x] Go

### LINKED ISSUE #535: Enums.py contains spurious whitespace
### What
#533 introduces spurious whitespace into the GAPIC generated file `enums.py`; in particular, there are sometimes 3 newlines in between top-level declarations instead of two.
### Why

I spent some time trying to rearrange the whitespace in `enum.snip` but found that alternative arrangements seemed to trigger a bug in the template language that caused the indentation to be wrong. It may need further investigation to determine what exactly triggers the bug, or whether it's possible to work around it.

The extra whitespace is does not make any difference to the behavior of the code, and hopefully it will be removed by the `yapf` Python formatter in `artman` anyway; therefore, categorizing as P3.

### PR DESCRIPTION
**Pull request by eoogbe**
Closes #348, closes #490, closes #535. Completes the migration to MVVM finally.

### CODE REVIEW

**Comment by eoogbe** [comment]
@lukesneeringer @shinfan PTAL

**Comment by eoogbe** [comment]
@geigerj I limited the enums output to reachable ones. That seems to be a bug that affected Ruby and NodeJS, but because Python wasn't using MVVM didn't affect Python.

**Comment by geigerj** [comment]
@eoogbe Got it. Thanks for clarifying.

**Comment by bjwatson** [comment]
Woo hoo! Great job, @eoogbe!

**Pull request merged**
