### PR TITLE
Allow java settings classes to be subclassed

### PR DESCRIPTION
**Pull request by igorbernstein2**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
@igorbernstein2 , the test baseline files need to be updated too so that the tests pass.

**Comment by igorbernstein2** [comment]
yep, sorry. This is still WIP, wasn't ready for review yet

**Comment by garrettjonesgoogle** [comment]
Oops, my fault for not noticing the WIP :-P

**Comment by igorbernstein2** [comment]
rebased & ready to be reviewed/merged

**Comment by igorbernstein2** [comment]
please merge

**Comment by igorbernstein2** [comment]
Thanks!

**Pull request merged**
