### PR TITLE
Setup to use gradle's protoc for generating protoc code.

### PR DESCRIPTION
**Pull request by jmuk**
Fixes issue #11 

Well, I'm actually not so familiar with gradle, but this passes java8 tests on travis (see https://travis-ci.org/jmuk/toolkit/jobs/125122347).

### CODE REVIEW

**Comment by pongad** [comment]
Oh wow I didn't think of that. There are still some Java 8 codes in here, so it makes sense that Java 7 won't compile. LGTM.

**Comment by tbetbetbe** [comment]
I think once this is in, #8 will fix the java8 issues

**Comment by jmuk** [comment]
Okay, let me merge this.

**Comment by tbetbetbe** [comment]
LGTM

**Comment by pongad** [comment]
@jmuk A side note, for commit messages, you can include text like "fix #<issue-number>" and GitHub will auto-close that issue for you. Unfortunately "fix issue #<issue-number>" doesn't work.

**Comment by jmuk** [comment]
Oh... thank you for telling me that.

**Pull request merged**
