### PR TITLE
Python wrappers: return proto Empty type

### LINKED ISSUE #760: [Python] Return empty messages (except protobuf.Empty)
### What:
The following Python methods should return a value (as their samples suggest):

https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/python_main_library.baseline#L1200
https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/python_main_library.baseline#L1168

### Why:
The API owners might intend to add content to these messages later, and we don't want our client libraries to break users as a result.

### How:
This appears to be the responsible code:
https://github.com/googleapis/toolkit/blob/master/src/main/java/com/google/api/codegen/py/PythonProtoElements.java#L35-L37

### PR DESCRIPTION
**Pull request by geigerj**
Previously returned None.

Fixes #760.

### CODE REVIEW

**Comment by geigerj** [comment]
Sorry, I realize now that we do not need to return `google.protobuf.Empty`, only *other* empty messages. I need to revise this PR.

**Comment by geigerj** [comment]
@jmuk @swcloud Since this is beta blocking for Python and @bjwatson is OOO, it would be great if one of you has time to do this review.

**Comment by geigerj** [comment]
@jmuk Thanks!

**Comment by swcloud** [comment]
Actually I think it's better use Empty.getDescriptor().getFullName() instead of using the hard-coded string. Also I think you should call MethodConfig.isReturnEmptyMessageMethod.

**Comment by geigerj** [comment]
@swcloud OK, I will make that change on a follow-up PR.

**Comment by bjwatson** [comment]
@geigerj Which PR or issue is this? Does this follow-up PR need to be done for beta?

**Comment by geigerj** [comment]
No, it is a style change. There is no impact on the surface. It was done in #797.

**Comment by bjwatson** [comment]
Got it. Thanks!

**Pull request merged**
