### PR TITLE
DO NOT COMMIT: Prototype getRepresentativeMethod

### PR DESCRIPTION
**Pull request by pongad**
Issue #245 is caused by the way we display a method sample in API doc.
We simply look for the first flattened method,
assume (most likely without meaning to) that it's not page-streaming,
and create a sample for it.

The issue itself can be resolved by properly detecting whether or not
the method page-streams. This can be done after MVVM to avoid duplicate
work.

But this begs the question: what the heck do we do if there is no
flattened method?

This commit prototypes a way to find a suitable method with the
following observations.
* we prefer flattened method; that's what users will probably use
* we prefer non-page-streaming methods; their samples are shorter
* we prefer methods with fewer arguments; initializations are shorter

How feasible do you think this approach is?

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Neat approach! I like it and I think it's worth rolling in.

**Comment by garrettjonesgoogle** [comment]
Could you transition this over to JavaGapicSurfaceTransformer? There is a `getExampleApiMethod` which you could replace with this implementation.

**Comment by pongad** [comment]
@garrettjonesgoogle I'm curious. Why is this Java-specific? Shouldn't the same method be chosen in any language?

**Comment by garrettjonesgoogle** [comment]
Other languages don't have the flattened/non-flattened distinction.

**Comment by pongad** [comment]
Superseded by #635

**Pull request closed without merging**
