### PR TITLE
Fix Python GAPIC package metadata output path

### PR DESCRIPTION
**Pull request by geigerj**
Previously, the template file's directory was mistakenly included in
the output path.

### CODE REVIEW

**Comment by lukesneeringer** [comment]
As soon as tests pass, I would like to merge this. It fixes a problem that is a prerequisite to the `protos`- change.

**Comment by geigerj** [comment]
Tests pass -- LGTY?

**Comment by lukesneeringer** [comment]
Looks good to me. I asked @landrito to give it a quick once-over so there is a second reviewer.

**Comment by landrito** [comment]
LGTM

**Pull request merged**
