### PR TITLE
Python docs have changed structure.

### PR DESCRIPTION
**Pull request by tswast**
I haven't updated tests, but I've allowed edits from maintainers if you wish to do so.

### CODE REVIEW

**Comment by tswast** [comment]
Ping. This appears to sill be relevant. The Python docs are reorganized.

**Comment by tswast** [comment]
@garrettjonesgoogle Could you find someone on the veneer team who can review/merge this README update?

**Comment by tswast** [comment]
Actually, I guess this one is a change to the Python generator. https://github.com/googleapis/toolkit/pull/1462 is a README update.

**Comment by lukesneeringer** [comment]
(About to check out the branch and update the tests.)

**Pull request merged**
