### PR TITLE
Manually update Ruby names file for compile check

### PR DESCRIPTION
**Pull request by tcoffee-google**
Based on latest discovery docs, also updated across all test APIs.

### CODE REVIEW

**Comment by tcoffee-google** [comment]
Hang on, left out commit updating baselines based on changed discoveries.

**Comment by tcoffee-google** [comment]
Should now be consistent.

**Comment by vchudnov-g** [comment]
Did  you verify that Ruby compilecheck passes? If so, LGTM.

**Comment by tcoffee-google** [comment]
As discussed offline, submitting despite current compile-check failures so we can update status.

**Pull request merged**
