### PR TITLE
Shorten some var names to be more idiomatic

### LINKED ISSUE #171: Shorten Go client vars to be more idiomatic
s/client/c
s/iterator/it

### PR DESCRIPTION
**Pull request by saicheems**
Resolves #171

### CODE REVIEW

**Comment by saicheems** [comment]
@jba 
@jmuk 
@pongad 
@vchudnov-g

**Comment by pongad** [comment]
Looks good to me. Make sure the generated test passes though!

**Comment by jmuk** [comment]
LGTM

**Comment by jba** [comment]
I like it. LGTM.

**Pull request merged**
