### PR TITLE
Update Ruby names and discovery docs

### PR DESCRIPTION
**Pull request by tcoffee-google**

### CODE REVIEW

**Comment by saicheems** [comment]
Hmm... will this discovery doc update now break other languages?

**Comment by vchudnov-g** [comment]
It might break the baseline tests, though it shouldn't of itself break compilecheck in production. It looks like @tcoffee-google ran the baseline tests and updated as needed, so IIUC, this should work.

LGTM

**Comment by tcoffee-google** [comment]
Yes, the baselines have been updated.

**Comment by tcoffee-google** [comment]
Note this will not resolve Ruby compile check issues until https://github.com/google/google-api-ruby-client/pull/482 is submitted, assuming no discovery docs have been updated in the meantime.

**Pull request merged**
