### PR TITLE
Revert a bunch of merge collateral damage

### PR DESCRIPTION
**Pull request by saicheems**

### CODE REVIEW

**Comment by saicheems** [comment]
PTAL, Garrett pointed out that I touched these files accidentally during my merge...

I reverted them to the commit before mine.

**Comment by garrettjonesgoogle** [comment]
LGTM assuming Travis passes

**Comment by shinfan** [comment]
This PR accidentally reverted some of my early changes.....

**Comment by saicheems** [comment]
UGHHHH

**Pull request merged**
