### PR TITLE
go: properly set headers in LRO methods

### PR DESCRIPTION
**Pull request by pongad**

### CODE REVIEW

**Comment by bjwatson** [comment]
@pongad LGTM, but @jba should also sign off. Also, sounds like all the GAPIC code needs to be regenerated... sorry about that.

**Comment by pongad** [comment]
@bjwatson Don't worry. Only speech and spanner :smile:

**Comment by bjwatson** [comment]
ok, cool

**Comment by bjwatson** [comment]
@jba Ping

**Pull request merged**
